### ISSUE TITLE
프로젝트 문서화, java docs 주석 추가, 부족한 기능 보완

### ISSUE THREAD

**Issue by prebird** [f-lab-edu/kyumall#53]
# 개요
- 프로젝트의 기능들을 소개하는 문서를 만듭니다.
- 소스코드에 java docs 주석을 추가하여 가독성을 증가시킵니다.

# TODO
- 회원(member) 파트
   - [x] Client 로직 문서화, 주석 추가
   - [ ] Admin 로직 문서화, 주석 추가
- 상품(product) 파트
   - [ ] Client 로직 문서화, 주석 추가
   - [ ] Admin 로직 문서화, 주석 추가
- 메인(main) 파트
  - [ ] Client 로직 문서화, 주석 추가
  - [ ] Admin 로직 문서화, 주석 추가
- 주문(order) 파트
  - [ ] Client 로직 문서화, 주석 추가
  - [ ] Admin 로직 문서화, 주석 추가
- 공통(common) 파트
  - [ ] Client 로직 문서화, 주석 추가
  - [ ] Admin 로직 문서화, 주석 추가
